[package]
name = "sf-model"
version = "0.1.0"
authors = ["Parker Snell <parkersnell@gmail.com>"]

[dependencies]
either = "1.1.0"
futures = "0.1.14"
serde = "*"
serde_json = "1.0"
serde_derive = "1.0"
log = "0.3.8"
sf-auth = {path = "../auth"}
sf-util = {path = "../util"}