[package]
name = "sf-vm"
version = "0.1.0"
authors = ["Parker Snell <parkersnell@gmail.com>"]

[[bin]]
path = "src/test.rs"
name = "vmtest"

[dependencies]
nom = {version = "3.2.0", features = ["nightly"]}
fxhash = "0.2.1"
log = "0.3.8"
lazy_static = "0.2.8"
