[package]
name = "scifi-http-server"
version = "0.1.0"
authors = ["Parker Snell <parkersnell@gmail.com>"]

[dependencies]
hyper = "0.11.1"
futures = "0.1.14"
log = "0.3.8"
scifi-model = {path = "../model"}
scifi-router = {path = "../router", features=["hyper"]}
scifi-util = {path = "../util"}